import type { CategorySlug, IncidentCategory } from './types.js';

export const CATEGORIES: readonly IncidentCategory[] = [
  {
    slug: 'roubo-celular',
    label: 'Roubo de celular',
    group: 'patrimonio',
    icon: 'smartphone',
    color: '#D2702F',
    riskWeight: 0.6,
    description: 'Subtração de celular com violência ou grave ameaça.',
  },
  {
    slug: 'furto-celular',
    label: 'Furto de celular',
    group: 'patrimonio',
    icon: 'smartphone',
    color: '#E0A93B',
    riskWeight: 0.4,
    description: 'Subtração de celular sem violência (ex.: descuido).',
  },
  {
    slug: 'assalto-mao-armada',
    label: 'Assalto à mão armada',
    group: 'patrimonio',
    icon: 'shield-alert',
    color: '#A8332F',
    riskWeight: 0.85,
    description: 'Roubo mediante uso de arma.',
  },
  {
    slug: 'tentativa-assalto',
    label: 'Tentativa de assalto',
    group: 'patrimonio',
    icon: 'shield',
    color: '#D2702F',
    riskWeight: 0.6,
    description: 'Tentativa de roubo não consumada.',
  },
  {
    slug: 'arrastao',
    label: 'Arrastão',
    group: 'patrimonio',
    icon: 'users',
    color: '#A8332F',
    riskWeight: 0.8,
    description: 'Ação coletiva de roubo a múltiplas vítimas.',
  },
  {
    slug: 'roubo-veiculo',
    label: 'Roubo de veículo',
    group: 'patrimonio',
    icon: 'car',
    color: '#A8332F',
    riskWeight: 0.8,
    description: 'Subtração de veículo com violência ou ameaça.',
  },
  {
    slug: 'furto-veiculo',
    label: 'Furto de veículo',
    group: 'patrimonio',
    icon: 'car',
    color: '#E0A93B',
    riskWeight: 0.55,
    description: 'Subtração de veículo sem violência.',
  },
  {
    slug: 'roubo-carga',
    label: 'Roubo de carga',
    group: 'patrimonio',
    icon: 'truck',
    color: '#A8332F',
    riskWeight: 0.8,
    description: 'Subtração de carga transportada.',
  },
  {
    slug: 'golpe',
    label: 'Golpe',
    group: 'patrimonio',
    icon: 'alert-triangle',
    color: '#E0A93B',
    riskWeight: 0.4,
    description: 'Fraude ou estelionato (presencial ou digital).',
  },
  {
    slug: 'disparo-arma',
    label: 'Disparo de arma de fogo',
    group: 'violencia_armada',
    icon: 'crosshair',
    color: '#A8332F',
    riskWeight: 0.9,
    description: 'Disparo de arma de fogo registrado.',
  },
  {
    slug: 'tiroteio',
    label: 'Tiroteio',
    group: 'violencia_armada',
    icon: 'crosshair',
    color: '#A8332F',
    riskWeight: 0.95,
    description: 'Troca de tiros em via ou área pública.',
  },
  {
    slug: 'confronto-policial',
    label: 'Confronto policial',
    group: 'violencia_armada',
    icon: 'siren',
    color: '#A8332F',
    riskWeight: 0.9,
    description: 'Operação ou confronto envolvendo forças de segurança.',
  },
  {
    slug: 'sequestro-relampago',
    label: 'Sequestro relâmpago',
    group: 'pessoa',
    icon: 'user-x',
    color: '#A8332F',
    riskWeight: 0.9,
    description: 'Privação de liberdade de curta duração para extorsão.',
  },
  {
    slug: 'violencia-contra-mulher',
    label: 'Violência contra mulher',
    group: 'pessoa',
    icon: 'heart-crack',
    color: '#A8332F',
    riskWeight: 0.85,
    description: 'Agressão física, psicológica ou sexual contra mulher.',
  },
  {
    slug: 'assedio',
    label: 'Assédio',
    group: 'pessoa',
    icon: 'user-minus',
    color: '#D2702F',
    riskWeight: 0.5,
    description: 'Assédio moral ou sexual em espaço público.',
  },
  {
    slug: 'vandalismo',
    label: 'Vandalismo',
    group: 'mobilidade',
    icon: 'spray-can',
    color: '#E0A93B',
    riskWeight: 0.35,
    description: 'Dano a patrimônio público ou privado.',
  },
  {
    slug: 'area-alagada',
    label: 'Área alagada',
    group: 'mobilidade',
    icon: 'waves',
    color: '#E0A93B',
    riskWeight: 0.45,
    description: 'Alagamento que afeta circulação ou imóveis.',
  },
  {
    slug: 'via-interditada',
    label: 'Via interditada',
    group: 'mobilidade',
    icon: 'construction',
    color: '#E0A93B',
    riskWeight: 0.3,
    description: 'Bloqueio ou interdicção de via.',
  },
  {
    slug: 'outro',
    label: 'Outro',
    group: 'outros',
    icon: 'help-circle',
    color: '#5A6470',
    riskWeight: 0.2,
    description: 'Ocorrência não classificada nas demais categorias.',
  },
];

export const CATEGORY_BY_SLUG: Record<CategorySlug, IncidentCategory> = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c]),
) as Record<CategorySlug, IncidentCategory>;

export function getCategory(slug: CategorySlug): IncidentCategory {
  const category = CATEGORY_BY_SLUG[slug];
  if (!category) throw new Error(`Categoria desconhecida: ${slug}`);
  return category;
}
